name: Run .NET Framework Tests and Publish Results

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore BaiTuanTuan3_NguyenChiTruong.sln

      - name: Build solution
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" BaiTuanTuan3_NguyenChiTruong.sln /p:Configuration=Release

      - name: Run tests using VSTest
        run: >
          "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
          BaiTuanTuan3_NguyenChiTruong\bin\Release\BaiTuanTuan3_NguyenChiTruong.dll
          /Logger:trx
          /ResultsDirectory:TestResults

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults/*.trx

      - name: Publish test results to GitHub UI
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: TestResults/*.trx
